name: Deploy to GitHub Pages

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref == 'refs/heads/master' && 'pages' || format('pages-{0}', github.sha) }}
  cancel-in-progress: false

jobs:
  lint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
      - name: Enable corepack for npm
        run: |
          corepack enable npm
      - name: Install
        run: |
          npm ci
      - name: Run eslint
        run: |
          npm run lint

  build:
    permissions:
      contents: read
      pages: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: gh-pages
        name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
      - name: Enable corepack for npm
        run: |
          corepack enable npm
      - name: Install
        run: |
          npm ci
      - name: Run Vitest tests
        run: |
          npm run test
      - name: Install Playwright browsers
        run: |
          npm run install:e2e
      - name: Build
        run: |
          npm run build -- --base "$BASE_PATH"/
        env:
          BASE_PATH: ${{ steps.gh-pages.outputs.base_path }}
      - name: Run Playwright tests
        run: |
          npm run test:e2e
        env:
          BASE_PATH: ${{ steps.gh-pages.outputs.base_path }}
        timeout-minutes: 10
      - name: Upload Playwright test report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist/

  deploy:
    needs: build
    if: github.ref == 'refs/heads/master'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
